# Generated by Django 5.0.3 on 2024-04-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_home_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='affiliate_link',
            field=models.CharField(default=1, max_length=2083),
            preserve_default=False,
        ),
    ]
