# Generated by Django 5.0.3 on 2024-04-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_home_affiliate_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='image_url',
        ),
        migrations.AddField(
            model_name='home',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='software_images'),
        ),
    ]
