# Generated by Django 5.0.3 on 2024-04-07 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_home_image_url_home_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
