# Generated by Django 5.0.3 on 2024-04-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
