# Generated by Django 5.0.3 on 2024-04-14 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
