# Generated by Django 5.0.3 on 2024-04-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='affiliate_link',
            field=models.CharField(blank=True, max_length=2083, null=True),
        ),
    ]
