# Generated by Django 5.0.3 on 2024-04-08 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_universallogo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UniversalLogo',
        ),
    ]
