# Generated by Django 5.0.3 on 2024-05-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_delete_universallogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
