# Generated by Django 5.0.3 on 2024-04-07 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_delete_home'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.SlugField(max_length=255)),
                ('introduction', models.TextField()),
                ('body', models.TextField()),
                ('conclusion', models.TextField()),
                ('affiliate_link', models.CharField(blank=True, max_length=2083, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item4_images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items4', to='core.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items4', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
