# Generated by Django 5.0.3 on 2024-04-15 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_item_is_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='conclusion',
        ),
    ]
