# Generated by Django 5.0.3 on 2024-04-06 17:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_software_affiliate_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='image',
        ),
        migrations.AddField(
            model_name='software',
            name='image_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=2083),
            preserve_default=False,
        ),
    ]
