# Generated by Django 5.0.3 on 2024-04-06 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_home_image_url_home_image'),
        ('software', '0004_category_item_delete_software'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
